development:
  username: bitcoin-admin
  password: 0fNbBeD3CY
  url: http://dev.netcook.org:8332/
  donations: 1FXWhKPChEcUnSEoFQ3DGzxKe44MDbatz
  
test:
  username: bitcoin-admin
  password: 0fNbBeD3CY
  url: http://dev.netcook.org:8332/
  donations: 1FXWhKPChEcUnSEoFQ3DGzxKe44MDbatz
